export const API_URL = "http://35.165.114.91:8081";

export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_DROPDOWN_LIST = 'GET_DROPDOWN_LIST';
export const DROPDOWN_LODING = 'DROPDOWN_LODING';
export const GET_DROPDOWN_RESULT = 'GET_DROPDOWN_RESULT';

export const GET_CUSTOMER_DROPDOWN_LIST = 'GET_CUSTOMER_DROPDOWN_LIST';
export const CUSTOMER_DROPDOWN_LODING = 'CUSTOMER_DROPDOWN_LODING';
export const GET_CUSTOMER_DROPDOWN_RESULT = 'GET_CUSTOMER_DROPDOWN_RESULT';

export const GRAPH_LOADING = 'GRAPH_LOADING';
export const BAR_GRAPH1 = 'BAR_GRAPH1';
export const BAR_GRAPH2 = 'BAR_GRAPH2';
export const LINE_GRAPH = 'LINE_GRAPH';
export const PIE_GRAPH = 'PIE_GRAPH';